### ISSUE TITLE
Yet another "failed to parse .ll file"

### ISSUE THREAD

**Issue by setupminimal** [japaric/cargo-call-stack#28]
I'm sorry to say that I'm running into another parser error. On the `fn` example:

```
Failure(("%0 = type { [0 x i32], i32, [0 x i32], i32, [0 x i32], i32, [0 x i32], i32, [0 x i32], i32, [0 x i32], i32, [0 x i32], i32, [0 x i32], i32, [0 x i32] } ...
```
on `cargo-call-stack` version `0.1.5` with cargo `1.48.0-nightly (9d1a4863a 2020-10-05)`. 

I get exactly the same error and first definition (although shorter output) on the minimal no-std rust program:

```
#![no_main]
#![no_std]

use cortex_m_rt::entry;

#[inline(never)]
#[entry]
fn main() -> ! {
    loop {}
}

#[panic_handler]
fn phandler(_: &core::panic::PanicInfo) -> ! {
    loop {}
}
```

I would be happy to try and fix this error myself, but I'm really not sure where to start. If I don't get more specific guidance I'll try adding a bunch of debugging print statements tomorrow after work to see if I can track down what's causing this.

**Comment by japaric** [comment]
snippet works with cargo-call-stack v0.1.7 and nightly-2022-06-15
