### ISSUE TITLE
`cargo-call-stack` fails to parse

### ISSUE THREAD

**Issue by datdenkikniet** [japaric/cargo-call-stack#33]
When trying to run [this project](https://github.com/datdenkikniet/test_rtic_0.6) through cargo-call-stack, an error is produced. 
The error message instructs me to include the first define item, but it's pretty long. I've included it in the repository for easier access, [here](https://github.com/datdenkikniet/test_rtic_0.6/blob/master/error).

My `cargo` version is `1.54.0-nightly (e51522ab3 2021-05-07)`, rustc `1.54.0-nightly (5c0292654 2021-05-11)` and cargo-call-stack `0.1.5`

I've tried to figure out what is going wrong, and where, but am having a hard time figuring out how to get some more useful output out of nom/the program besides the entire `define` block.

A fix, or pointers on how to figure out where exactly the error is occurring, are greatly appreciated!

**Comment by taqtiqa-mark** [comment]
I'm seeing similar failure:

```rust
BUG: failed to parse .ll file: Failure(("define internal fastcc void @_Z....
```

however with this simplified code:

```rust
use lazy_static::lazy_static;
use rand::distributions::{Distribution, Uniform};
use std::time::Duration;
use tokio::time::{sleep, Instant};

lazy_static! { static ref START_TIME: Instant = Instant::now(); }

#[tokio::main]
async fn main() {
    let page = get_page(42).await;
    println!("Page #42: {:?}", page);
}

async fn get_page(i: usize) -> Vec<usize> {
    let millis = Uniform::from(5_000..6_000).sample(&mut rand::thread_rng());
    println!( "[{}] # get_page({}) will complete in {} ms on {:?}",
        START_TIME.elapsed().as_millis(),
        i,
        millis,
        std::thread::current().id()
    );

    sleep(Duration::from_millis(millis)).await;
    println!("[{}] # get_page({}) completed",
        START_TIME.elapsed().as_millis(),
        i
    );
    (10 * i..10 * (i + 1)).collect()
}
```

The [error log is here.](https://gist.github.com/taqtiqa-mark/8c4122c0f4e7282ff78feb1cb65b1d15)

```bash
$ rustc --version --verbose
rustc 1.56.0-nightly (5ad7389bd 2021-08-06)
binary: rustccommit-hash: 5ad7389bdd1abe7d2c6f73a233af1a7a69e96285
commit-date: 2021-08-06
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 12.0.1
```

**Comment by japaric** [comment]
I can't `cargo build` the code but try cargo-call-stack v0.1.7 and nightly-2022-06-15 after fixing the compilation errors and open a new issue if cargo-call-stack doesn't work.
