### ISSUE TITLE
build failure on stm32

### ISSUE THREAD

**Issue by aholtzma-am** [japaric/cargo-call-stack#55]
While trying to run this on an STM32L0x project we get the following error:

```
$ cargo  +nightly call-stack --bin STM32_controller
   Compiling gimli v0.25.0
error[E0432]: unresolved import `alloc::sync`
 --> /Users/aholtzma/.cargo/registry/src/github.com-1ecc6299db9ec823/gimli-0.25.0/src/read/dwarf.rs:2:12
  |
2 | use alloc::sync::Arc;
  |            ^^^^ could not find `sync` in `alloc`

error[E0282]: type annotations needed
  --> /Users/aholtzma/.cargo/registry/src/github.com-1ecc6299db9ec823/gimli-0.25.0/src/read/dwarf.rs:97:18
   |
97 |             sup: None,
   |                  ^^^^ cannot infer type for type parameter `T` declared on the enum `Option`

error[E0283]: type annotations needed
  --> /Users/aholtzma/.cargo/registry/src/github.com-1ecc6299db9ec823/gimli-0.25.0/src/read/dwarf.rs:60:5
   |
21 | #[derive(Debug, Default)]
   |                 ------- in this derive macro expansion
...
60 |     pub sup: Option<Arc<Dwarf<R>>>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type
   |
   = note: cannot satisfy `_: Default`
   = note: this error originates in the derive macro `Default` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0282, E0283, E0432.`
```

It's not clear what even uses gimli, so I'm a bit at a loss where to go from here.

**Comment by japaric** [comment]
are you compiling `gimli` for `thumbv6m-none-eabi`? I don't think `gimli` can be compiled for `thumbv6m-none-eabi` if its "read" Cargo feature is enabled. Does `cargo +nightly build --bin STM32_controller` compile?

**Comment by japaric** [comment]
after digging some more it seems that the full version of `-Z build-std` is broken for ARMv6-M and has been like that for a while -- that's an upstream (libstd) issue. for no-std targets we should use `-Z build-std=core` (or `=alloc`). I think we may be able to look at `rustc --print cfg --target $T` and check if `target_os="none"` is there to check if the target is no-std.
