### ISSUE TITLE
BUG: failed to parse LLVM IR

### ISSUE THREAD

**Issue by forty** [japaric/cargo-call-stack#58]
Hello,

**Error**

I get the following message on my project

```
error: failed to parse application's LLVM IR from `project/target/x86_64-unknown-linux-gnu/release/deps/bin-0d269819aa1d3063.ll`: BUG: failed to parse LLVM IR; please submit a cargo-call-stack bug report and attach the `.ll` file: Failure("Eof in line 880")
```
**Info**

```
$ cargo +nightly call-stack  --version
cargo-call-stack 0.1.7
$ cargo --version
cargo 1.61.0 (a028ae4 2022-04-29)
$ rustc --version
rustc 1.61.0 (fe5b13d68 2022-05-18)
```

[bin-0d269819aa1d3063.ll.txt](https://github.com/japaric/cargo-call-stack/files/8953034/bin-0d269819aa1d3063.ll.txt)

Let me know if I can help figuring it out.

thanks!

**Comment by japaric** [comment]
with PR #59 the llvm-ir parser can handle the `.ll` file you shared in the issue description

**Comment by forty** [comment]
Who thanks for the super fast reply. I don't have this error anymore, but now it fails on a different problem

```
thread 'main' panicked at 'BUG: unhandled llvm intrinsic: llvm.experimental.noalias.scope.decl', /home/forty/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-call-stack-0.1.8/src/main.rs:701:21
```
This ` llvm.experimental.noalias.scope.decl` seem to indeed be present in the file I shared (but if it's supposed to work, maybe I'm doing something wrong?)

Thanks!

**Comment by japaric** [comment]
I only ran your file through the llvm-ir parser; I couldn't test the whole cargo-call-stack itself because I didn't have the source code of your Cargo project. I can repro the issue with a "hello, world" project; will have a look.
